language: python
sudo: true
addons:
    postgresql: "9.6"

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"

matrix:
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "nightly"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install -U pip
  - pip install wheel
  - pip install psycopg2
  - pip install sqlalchemy
  - pip install flake8
  - pip install coverage
  - pip install nose
  - pip install coveralls
  - python setup.py develop

script:
  - flake8 powerscan_scenario
  - psql -c 'create database powerscan_scenario;' -U postgres
  - nosetests powerscan_scenario/tests -v -s --with-coverage --cover-package=powerscan_scenario
  
after_success:
  coveralls
